package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import models.ModelTableOrders;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class manageOrdersController implements Initializable{
		
	Connection con = null;
    PreparedStatement st = null, st1=null;
    ResultSet rs = null, rs1=null;
    @Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
		loggedUser.setText(LoginController.getLoggedUserName());
		try {
			con = DriverManager.getConnection("jdbc:mysql://b89b4675b5cd41:7a58b101@us-cdbr-east-03.cleardb.com/heroku_3cdd412dc4ff1f0?reconnect=true");
	    	SelectOrders();			
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}    
    
	@FXML
	private Text loggedUser;
	@FXML
	private Button homeButton;

	@FXML
    private TableView<ModelTableOrders> OrderTable;

    @FXML
    private TableColumn<ModelTableOrders, String> col_s_no;

    @FXML
    private TableColumn<ModelTableOrders, String> col_prod_id;

    @FXML
    private TableColumn<ModelTableOrders, String> col_prod_name;

    @FXML
    private TableColumn<ModelTableOrders, String> col_qty;

    @FXML
    private TableColumn<ModelTableOrders, String> col_cust_id;

    @FXML
    private TableColumn<ModelTableOrders, String> col_cust_name;
	@FXML
	private TextField orderID;
	@FXML
	private TextField productID;
	@FXML
	private TextField productName;
	@FXML
	private TextField qtyOrdered;
	@FXML
	private TextField custID;
	@FXML
	private TextField custName;
	@FXML
	private Button orderReceived;
	@FXML
	private Button addBack;
	@FXML
	private Button clearFields;
	@FXML
    private Button logoutButton;

	@FXML
    void logoutButtonPressed(ActionEvent event) throws SQLException {		
	
		Alert alert = new Alert(AlertType.CONFIRMATION, "Do you want to logout?", ButtonType.YES, ButtonType.NO);
		alert.setHeaderText("");
		alert.showAndWait();
		if (alert.getResult() == ButtonType.YES)
		{	
			con.close();
			System.exit(0);
		}	
    }
	
	// Event Listener on Button[#homeButton].onAction
	@FXML
	public void homeButtonPressed(ActionEvent event) throws IOException {
		// TODO Autogenerated
		Parent userView = FXMLLoader.load(getClass().getResource("/View/adminHome.fxml"));
		Scene userScene = new Scene(userView);
		Stage window = (Stage)((Node)event.getSource()).getScene().getWindow();		
		window.setScene(userScene);
		window.show();
	}
	
	// Event Listener on TableView[#OrderTable].onMouseClicked
	@FXML
	public void setCellValue(MouseEvent event) {
		// TODO Autogenerated		
		ModelTableOrders data=OrderTable.getSelectionModel().getSelectedItem();
		if (data!=null)
		{
			orderID.setText(data.getId());
			productID.setText(data.getPid());
			productName.setText(data.getPname());
			qtyOrdered.setText(data.getQty());
			custID.setText(data.getCustid());
			custName.setText(data.getCustname());
		}
	}
	
	// Event Listener on Button[#orderReceived].onAction
	@FXML
	public void orderReceivedButtonPressed(ActionEvent event) throws SQLException {
		
		if(orderID.getText().equals(""))
        {
            Alert alert=new Alert(AlertType.ERROR, "Please select an order from list to process!");
            alert.show();
        }
		else
		{		
			Alert alert = new Alert(AlertType.CONFIRMATION, "Are you Sure?", ButtonType.YES, ButtonType.NO);
			alert.setHeaderText("Have you received this order from " + custName.getText() + " ?");
			alert.showAndWait();
	
			if (alert.getResult() == ButtonType.YES)
			{
				String query = "delete from productordered where id=?";		           
                st = con.prepareStatement(query);
                st.setInt(1, Integer.parseInt(orderID.getText()));
                st.execute();                
                
                OrderTable.getItems().clear();
                SelectOrders();
                clearFields.fire();
                
                alert=new Alert(AlertType.INFORMATION, "Order processed sucessfully!");
                alert.show();                                
			}
		}
	}
	
	// Event Listener on Button[#addBack].onAction
	@FXML
	public void addBackButtonPressed(ActionEvent event) throws SQLException 
	{
		// TODO Autogenerated		
		if(orderID.getText().equals(""))
        {
            Alert alert=new Alert(AlertType.ERROR, "Please select an order from list to process!");
            alert.show();
        }
		else
		{		
			Alert alert = new Alert(AlertType.CONFIRMATION, "are you sure to add it back to requirements list?", ButtonType.YES, ButtonType.NO);
			alert.setHeaderText("This Order not received from " + custName.getText() + " ?");
			alert.showAndWait();
	
			if (alert.getResult() == ButtonType.YES)
			{
				//First check if Product is available in database				
				int quantityInDB=0;
				String query = "SELECT id from product where id=?";				
                st = con.prepareStatement(query);
                st.setInt(1, Integer.parseInt(productID.getText()));
                rs=st.executeQuery(); 
                if (rs.next()) 
                {
                	//Product is available in database, so just update the quantity
                	//first get the quantity from database
                	String query1 = "SELECT * from product";
                	st = con.prepareStatement(query1);
                	rs1=st.executeQuery();
                	while(rs1.next())
                	{
                		if(rs1.getInt("id") == Integer.parseInt(productID.getText()))
                		{
                			quantityInDB=Integer.parseInt(rs1.getString("quantity"));
                		}
                	}
                	
                	//adding the quantity from database and ordered by user to add it back
                	int newQuantity=quantityInDB+Integer.parseInt(qtyOrdered.getText());  
                	query = "update product set quantity=? where id=?";
                    st = con.prepareStatement(query);
                    st.setInt(1, newQuantity);
                    st.setInt(2, Integer.parseInt(productID.getText()));
                    st.execute(); 
                    
                    alert=new Alert(AlertType.INFORMATION, "Product added back to list!");
                    alert.show();                	
                } 
                else
                {
                	//if product not found in the list add it as a new product
                	query = "INSERT INTO product VALUES (?,?,?)";
                    st = con.prepareStatement(query);
                    st.setInt(1, Integer.parseInt(productID.getText()));
                    st.setString(2, productName.getText());
                    st.setInt(3, Integer.parseInt(qtyOrdered.getText()));
                    st.execute();    
                    
                    alert=new Alert(AlertType.INFORMATION, "Product added back to list!");
                    alert.show();
                }
                
                //after adding the product back to list, remove it from the order list
                query = "delete from productordered where id=?";		           
                st = con.prepareStatement(query);
                st.setInt(1, Integer.parseInt(orderID.getText()));
                st.execute(); 
                OrderTable.getItems().clear();
                SelectOrders();
                clearFields.fire();                
			}
		}
	}
	
	// Event Listener on Button[#clearFields].onAction
	@FXML
	public void clearFieldsButtonPressed(ActionEvent event) {
		
		orderID.setText("");
		productID.setText("");
		productName.setText("");
		qtyOrdered.setText("");
		custID.setText("");
		custName.setText("");
	}
	
	
	ObservableList<ModelTableOrders> oblist= FXCollections.observableArrayList();
	public void SelectOrders() throws SQLException
    {
		String query = "SELECT * from productordered";
        st = con.prepareStatement(query);
        rs = st.executeQuery(); 
        while(rs.next())
        {
        	oblist.add(new ModelTableOrders(rs.getString("id"), rs.getString("productID"), rs.getString("productName"), rs.getString("quantity"), rs.getString("customerID"), rs.getString("customerName")));
        }	    
        col_s_no.setCellValueFactory(new PropertyValueFactory<>("id"));
        col_prod_id.setCellValueFactory(new PropertyValueFactory<>("pid"));
        col_prod_name.setCellValueFactory(new PropertyValueFactory<>("pname"));
        col_qty.setCellValueFactory(new PropertyValueFactory<>("qty"));
        col_cust_id.setCellValueFactory(new PropertyValueFactory<>("custid"));
        col_cust_name.setCellValueFactory(new PropertyValueFactory<>("custname"));
	    
	    OrderTable.setItems(oblist);      
    }
}
